### ISSUE TITLE
How to run dev server?

### ISSUE THREAD

**Issue by MarvinXu** [samchon/backend-template#182]
I can't access the api server either by running `npm run dev` or `npm run start`

open `http://127.0.0.1:37001/` got an ERR_CONNECTION_REFUSED

PS: I have connected to my database and got schema created by `npm run schema`, and there is no error in the console

**Comment by samchon** [comment]
I'm testing backend server only by `npm run test` command, and do not opening dev server for manual testing.

If you want to do that, just run both of them:

- `npm run build:main`
- `npm start`

**Comment by MarvinXu** [comment]
I ran the above commands but still can't access the api.
![image](https://github.com/samchon/backend/assets/7382357/d2343cd6-e417-4ab3-b9ff-5209eec44db0)

![image](https://github.com/samchon/backend/assets/7382357/44e35e7b-2d58-4ac0-b532-d1b42018b433)

**Comment by samchon** [comment]
Because your have not defined the `/` path.

**Comment by MarvinXu** [comment]
But shouldn't it at least return a 404 response? I tried `http://localhost:37001/monitors/performance`, still the same.

**Comment by samchon** [comment]
![image](https://github.com/samchon/backend/assets/13158709/ee8db883-3438-4519-a1b6-eb1f14747f03)

Working fine.

```bash
git clone https://github.com/samchon/backend
pnpm i
npm run build:main
npm start
```

**Comment by MarvinXu** [comment]
Got it working by adding hostname `0.0.0.0`. My server is running in WSL.
```ts
await this.application_.listen(MyConfiguration.API_PORT(), '0.0.0.0');
```

**Comment by samchon** [comment]
Okay, I'll adjust your case. Thanks for reporting.
